### ISSUE TITLE
QuakeLabeler ModuleNotFoundError

### ISSUE THREAD

**Issue by PANXIONG-CN** [maihao14/QuakeLabeler#4]
I followed the installation instructions to install the fascinating QuakeLabeler package
But I encountered an error as follows
`Traceback (most recent call last):
  File "/home/panxiong/anaconda3/envs/ql/bin/QuakeLabeler", line 5, in <module>
    from quakelabeler.scripts.QuakeLabeler import main
ModuleNotFoundError: No module named 'quakelabeler.scripts'`
Please give me a solution, thanks.

**Comment by maihao14** [comment]
Here's a quick solution:
Try: 
`pip install -e .`
to replace:
`pip install .`

in the last step of installation. Then the problem will be solved.

**Comment by PANXIONG-CN** [comment]
it works, thank you
